/**
 * Worker thread responsible for processing multiplicative persistence data,
 * updating runtime statistics, generating logs, and signaling readiness back
 * to the main thread.
 *
 * This worker uses a lightweight semaphore mechanism via `process.env.isWorkerReady`
 * to indicate when it has finished processing the latest message. The main thread
 * only sends new messages when the worker is idle.
 *
 * Message types handled:
 *  - 'init': Initialize worker state, logging, and callback functions.
 *  - 'stack': Accumulate message batches for later processing.
 *  - 'found': Process all stacked messages, update statistics, generate logs,
 *             and persist updated initialization variables.
 *
 * The worker never blocks. Every message ends by setting
 * `process.env.isWorkerReady = 'true'` to signal that the worker is idle.
 */

import { initConfig } from './Config/config.js'
import HugeInt from './HugeInt/index.js'
import calcCellsArrFactorial from './utils/calcCellsArrFactorial.js'
import factorial from './utils/factorial.js'
import logMultiPersistence from './MultiplicativePersistence/logMultiPersistence.js'
import { parentPort } from 'worker_threads'
import { setComputationState } from './Config/computationStateIO.js'

initConfig()

/**
 * Numerical base used for HugeInt operations.
 * @type {BigInt}
 */
let base

/**
 * Initialization variables shared with the main thread.
 * @type {ComputationState}
 */
let computationState

/**
 * Logging function generated by logMultiPersistence().
 * Produces a formatted log string for the main thread.
 * @type {(data: Object) => string}
 */
let log

/**
 * Callback invoked whenever a number is found during persistence search.
 * @type {onFoundCallback}
 */
let onFound

/**
 * Timestamp when the session started.
 * @type {number}
 */
let startSessionTime

/**
 * Adjusted timestamp including previous uptime.
 * @type {number}
 */
let startTime

/**
 * Accumulated message batches waiting to be processed.
 * Each entry is an array of FoundMessage objects.
 * @type {FoundMessage[][]}
 */
let stackMessages = []

/**
 * @typedef {Object} FoundMessage
 * @property {string} currentNoStr - String representation of the number found.
 * @property {number} steps - Number of persistence steps.
 * @property {number} atRunTime - Runtime at the moment of discovery.
 * @property {number} calcIterations - Total calculated iterations.
 * @property {BigInt} additionSum
 * @property {BigInt} multiplySum
 */

/**
 * Callback signature for handling found numbers.
 *
 * @callback onFoundCallback
 * @param {FoundMessage} foundMessage
 * @param {HugeInt} currentNo
 * @param {number} length - Number length
 * @param {number} startTime
 * @param {number} endTime
 */

/**
 * Creates an array of digit-counts for factorial combination calculations.
 *
 * @param {HugeInt} currentNo
 * @returns {BigInt[]} Array of digit counts.
 */
const createLengthsArray = (currentNo) => {
    const array = []
    let cell = currentNo.firstCell

    while (cell) {
        if (cell.count !== 1n) array.push(cell.count)
        cell = cell.next
    }

    if (array.length === 0) array.push(1n)
    return array
}

/**
 * Creates the onFound callback function bound to the current InitVars object.
 *
 * @param {ComputationState} computationState
 * @returns {onFoundCallback}
 */
const onFoundCreator = (computationState) => {
    const { steps: countSteps, number_lengths } = computationState

    return ({ atRunTime, calcIterations, steps, additionSum, multiplySum }, currentNo, length, startTime, endTime) => {
        const currentNoValue = currentNo.value

        // Initialize step statistics if missing
        if (!countSteps[steps]) {
            countSteps[steps] = {
                additionSum: 0n,
                multiplySum: 0n,
                atRunTime,
                combinations: 0n,
                count: 0,
                first: {
                    additionSum,
                    multiplySum,
                    currentNoValue,
                },
                iteration: 0,
                last: {
                    additionSum,
                    multiplySum,
                    currentNoValue,
                },
                step: steps,
            }
        }

        const countStep = countSteps[steps]
        const lengthsArr = createLengthsArray(currentNo)
        const combinations = factorial(BigInt(length)) / calcCellsArrFactorial(lengthsArr)

        countStep.additionSum += additionSum
        countStep.multiplySum += multiplySum
        countStep.combinations += combinations
        countStep.count++
        countStep.last = {
            additionSum,
            multiplySum,
            currentNoValue,
        },
        countStep.atRunTime = atRunTime
        countStep.iteration = calcIterations

        // Initialize number-length statistics if missing
        if (!number_lengths[length]) {
            number_lengths[length] = {
                found: 0,
                time: endTime - startTime,
                steps: {}
            }
        }

        const numberLength = number_lengths[length]

        if (!numberLength.steps[steps]) {
            numberLength.steps[steps] = {
                additionSum: 0n,
                multiplySum: 0n,
                count: 0,
                combinations: 0n,
                first: {
                    additionSum,
                    multiplySum,
                    currentNoValue,
                },
                last: {
                    additionSum,
                    multiplySum,
                    currentNoValue,
                },
            }
        }

        const numberLengthSteps = numberLength.steps[steps]
        numberLengthSteps.additionSum += additionSum
        numberLengthSteps.multiplySum += multiplySum
        numberLengthSteps.last = {
            additionSum,
            multiplySum,
            currentNoValue,
        }
        numberLengthSteps.count++
        numberLengthSteps.combinations += combinations
        numberLength.found++
    }
}

/**
 * @typedef {Object} MessageObj
 * @property {string} type - Message type ('init', "stack", "found")
 * @property {WorkerConfig,FoundMessage} data - Message payload
 */

/**
 * Main message handler for worker thread.
 *
 * @param {MessageObj} messageObj
 * @returns {Promise<void>}
 */
const onMessage = async (messageObj) => {
    const { type } = messageObj

    switch (type) {

        case 'init': {
            const config = messageObj.data
            base = config.base
            computationState = config.VARS
            startSessionTime = config.startSessionTime
            startTime = config.startTime

            const goalNumber = new HugeInt(config.goalNumber, base)
            log = logMultiPersistence({ goalNumber, base })
            onFound = onFoundCreator(computationState)
            break
        }

        case 'stack': {
            /** @type {FoundMessage[]} */
            const foundMessages = messageObj.data.messages
            stackMessages.push(foundMessages)
            delete messageObj.data
            break
        }

        case 'found': {
            const found = messageObj.data
            const {
                calcIterations,
                countIterations,
                currentNo,
                endTime,
                notFoundLimit,
                messages,
                notFound,
            } = found

            let noOfMessages = 0
            stackMessages.push(messages)

            // Process all stacked message batches
            const currentNoObj = new HugeInt(0n, base)

            for (const batch of stackMessages) {
                for (const message of batch) {
                    currentNoObj.fromString(message.currentNoStr, base)
                    onFound(message, currentNoObj, message.currentNoStr.length, startTime, endTime)
                }
                noOfMessages += batch.length
            }

            stackMessages = []

            // Update iteration statistics
            /** @type {Iterations} */
            computationState.iterations = {
                calculated: calcIterations,
                count: countIterations,
                found_nothing: notFound,
                found_nothing_break_at: notFoundLimit,
            }

            computationState.last_number = currentNo
            computationState.up_time = endTime - startTime
            delete found.messages

            // Generate log snapshot
            process.env.log = log({
                ...found,
                countSteps: computationState.steps,
                messagesCount: noOfMessages,
                lengths: computationState.number_lengths,
                startSessionTime,
                startTime,
            })
            await setComputationState(computationState, base)
            break
        }
    }

    // Signal readiness for next message
    process.env.isWorkerReady = 'true'
}

parentPort.on('message', onMessage)
