import path from 'path'
import {readJsonFileSync, writeJsonFile} from "./fileUtils.js";

/**
 * Custom JSON replacer used to serialize BigInt values when saving the cache
 * to disk. BigInts are converted to strings because JSON does not support
 * BigInt natively.
 *
 * @param {string} key
 *     The property key being serialized.
 *
 * @param {*} value
 *     The value associated with the key.
 *
 * @returns {*}
 *     A JSON‑safe representation of the value.
 */
const replacer = (key, value) => {
    const name = value?.constructor?.name
    if (name === 'BigInt') {
        return value.toString()
    }
    return value
}
/**
 * Custom JSON reviver used to deserialize BigInt values when loading the cache
 * from disk. The reviver toggles between normal values and BigInt conversion
 * based on parse order.
 *
 * This approach works because the serialized cache is an array of `[key, value]`
 * pairs, and the reviver is invoked in a predictable sequence.
 *
 * @returns {function(string, *): *}
 *     A reviver function suitable for JSON.parse().
 */
const reviver = () => {
    let toggle = 0
    return (key, value) => {
        toggle++
        if (toggle === 2) {
            toggle = -1
            return BigInt(value)
        }
        return value
    }
}

/**
 * Save a Map instance to a JSON file. The map is converted into an array of
 * `[key, value]` entries and serialized using the custom BigInt replacer.
 *
 * @param {string} filename
 *     Absolute path to the cache file.
 *
 * @param {Map<string, BigInt>} map
 *     The memoization cache to save.
 *
 * @returns {void}
 */
export function saveMapToFile(filename, map) {
    writeJsonFile(filename, Array.from(map.entries()), replacer, '\t').then()
}

/**
 * Load a memoization cache from a JSON file. If the file exists, it is parsed
 * using the custom BigInt reviver and converted back into a Map. The entries
 * are sorted to ensure deterministic ordering.
 *
 * If the file does not exist or cannot be parsed, an empty Map is returned.
 *
 * @param {string} filename
 *     Absolute path to the cache file.
 *
 * @returns {Map<string, BigInt>}
 *     The loaded memoization cache.
 */
export function loadMapFromFileSync(filename) {
    try {
        const json = readJsonFileSync(filename, reviver(), [])
        const entries = json.sort((a, b) => {
            if (a[0] > b[0]) return 1
            if (a[0] < b[0]) return -1
            return 0
        })
        const map = new Map(entries)
        saveMapToFile(filename, map)
        return map
    }
    catch (e) {
        return new Map()
    }
}

/**
 * Memoize a function and persist its results to disk.
 *
 * The memoization key is generated by joining all arguments into a single
 * string. Results are stored in a Map and periodically saved to a JSON file
 * inside the `./caching` directory.
 *
 * Behavior:
 *  - Loads existing cache from disk on initialization.
 *  - Stores new results in memory and writes them to disk every N calls,
 *    where N is defined by `process.normalizedEnv.memorize_save_bach`.
 *  - BigInt values are safely serialized/deserialized.
 *
 * @param {function(...*): BigInt} fn
 *     The function to memoize. Must return a BigInt.
 *
 * @param {string} name
 *     The name of the cache file (e.g., "getPermutations").
 *
 * @returns {function(...*): BigInt}
 *     A memoized version of the function.
 */
export default function memorize(fn, name) {
    const { normalizedEnv } = process

    const saveToFile = normalizedEnv.memorize_save_bach

    const fileName =  path.join(path.resolve('./caching'), `${name}.json`)

    const cache = loadMapFromFileSync(fileName)
    let setCounter = 0

    return function (...args) {
        const key = args.join()
        let data = cache.get(key)
        if (data) return data
        data = fn(...args)
        cache.set(key, data)
        setCounter++
        if (!(setCounter % saveToFile))
            saveMapToFile(fileName, cache)
        return data
    }
}
